-- Service area seed: Orange, Riverside, San Diego, and Los Angeles counties (CA)
-- Generated: 2026-06-16
-- Source: zipcodestogo.com and zip-codes.com county ZIP code lists
-- Apply via Supabase SQL Editor on project qamfxqbtvwwlzlmqrqbh

INSERT INTO service_areas (zip, city, state, is_active, name)
VALUES
  -- Orange County, CA,
  ('90620', 'Buena Park', 'CA', true, 'Buena Park'),
  ('90621', 'Buena Park', 'CA', true, 'Buena Park'),
  ('90622', 'Buena Park', 'CA', true, 'Buena Park'),
  ('90623', 'La Palma', 'CA', true, 'La Palma'),
  ('90624', 'Buena Park', 'CA', true, 'Buena Park'),
  ('90630', 'Cypress', 'CA', true, 'Cypress'),
  ('90631', 'La Habra', 'CA', true, 'La Habra'),
  ('90632', 'La Habra', 'CA', true, 'La Habra'),
  ('90633', 'La Habra', 'CA', true, 'La Habra'),
  ('90680', 'Stanton', 'CA', true, 'Stanton'),
  ('90720', 'Los Alamitos', 'CA', true, 'Los Alamitos'),
  ('90721', 'Los Alamitos', 'CA', true, 'Los Alamitos'),
  ('90740', 'Seal Beach', 'CA', true, 'Seal Beach'),
  ('90742', 'Sunset Beach', 'CA', true, 'Sunset Beach'),
  ('90743', 'Surfside', 'CA', true, 'Surfside'),
  ('92602', 'Irvine', 'CA', true, 'Irvine'),
  ('92603', 'Irvine', 'CA', true, 'Irvine'),
  ('92604', 'Irvine', 'CA', true, 'Irvine'),
  ('92605', 'Huntington Beach', 'CA', true, 'Huntington Beach'),
  ('92606', 'Irvine', 'CA', true, 'Irvine'),
  ('92607', 'Laguna Niguel', 'CA', true, 'Laguna Niguel'),
  ('92609', 'El Toro', 'CA', true, 'El Toro'),
  ('92610', 'Foothill Ranch', 'CA', true, 'Foothill Ranch'),
  ('92612', 'Irvine', 'CA', true, 'Irvine'),
  ('92614', 'Irvine', 'CA', true, 'Irvine'),
  ('92615', 'Huntington Beach', 'CA', true, 'Huntington Beach'),
  ('92616', 'Irvine', 'CA', true, 'Irvine'),
  ('92617', 'Irvine', 'CA', true, 'Irvine'),
  ('92618', 'Irvine', 'CA', true, 'Irvine'),
  ('92619', 'Irvine', 'CA', true, 'Irvine'),
  ('92620', 'Irvine', 'CA', true, 'Irvine'),
  ('92623', 'Irvine', 'CA', true, 'Irvine'),
  ('92624', 'Capistrano Beach', 'CA', true, 'Capistrano Beach'),
  ('92625', 'Corona Del Mar', 'CA', true, 'Corona Del Mar'),
  ('92626', 'Costa Mesa', 'CA', true, 'Costa Mesa'),
  ('92627', 'Costa Mesa', 'CA', true, 'Costa Mesa'),
  ('92628', 'Costa Mesa', 'CA', true, 'Costa Mesa'),
  ('92629', 'Dana Point', 'CA', true, 'Dana Point'),
  ('92630', 'Lake Forest', 'CA', true, 'Lake Forest'),
  ('92637', 'Laguna Woods', 'CA', true, 'Laguna Woods'),
  ('92646', 'Huntington Beach', 'CA', true, 'Huntington Beach'),
  ('92647', 'Huntington Beach', 'CA', true, 'Huntington Beach'),
  ('92648', 'Huntington Beach', 'CA', true, 'Huntington Beach'),
  ('92649', 'Huntington Beach', 'CA', true, 'Huntington Beach'),
  ('92650', 'East Irvine', 'CA', true, 'East Irvine'),
  ('92651', 'Laguna Beach', 'CA', true, 'Laguna Beach'),
  ('92652', 'Laguna Beach', 'CA', true, 'Laguna Beach'),
  ('92653', 'Laguna Hills', 'CA', true, 'Laguna Hills'),
  ('92654', 'Laguna Hills', 'CA', true, 'Laguna Hills'),
  ('92655', 'Midway City', 'CA', true, 'Midway City'),
  ('92656', 'Aliso Viejo', 'CA', true, 'Aliso Viejo'),
  ('92657', 'Newport Coast', 'CA', true, 'Newport Coast'),
  ('92658', 'Newport Beach', 'CA', true, 'Newport Beach'),
  ('92659', 'Newport Beach', 'CA', true, 'Newport Beach'),
  ('92660', 'Newport Beach', 'CA', true, 'Newport Beach'),
  ('92661', 'Newport Beach', 'CA', true, 'Newport Beach'),
  ('92662', 'Newport Beach', 'CA', true, 'Newport Beach'),
  ('92663', 'Newport Beach', 'CA', true, 'Newport Beach'),
  ('92672', 'San Clemente', 'CA', true, 'San Clemente'),
  ('92673', 'San Clemente', 'CA', true, 'San Clemente'),
  ('92674', 'San Clemente', 'CA', true, 'San Clemente'),
  ('92675', 'San Juan Capistrano', 'CA', true, 'San Juan Capistrano'),
  ('92676', 'Silverado', 'CA', true, 'Silverado'),
  ('92677', 'Laguna Niguel', 'CA', true, 'Laguna Niguel'),
  ('92678', 'Trabuco Canyon', 'CA', true, 'Trabuco Canyon'),
  ('92679', 'Trabuco Canyon', 'CA', true, 'Trabuco Canyon'),
  ('92683', 'Westminster', 'CA', true, 'Westminster'),
  ('92684', 'Westminster', 'CA', true, 'Westminster'),
  ('92685', 'Westminster', 'CA', true, 'Westminster'),
  ('92688', 'Rancho Santa Margarita', 'CA', true, 'Rancho Santa Margarita'),
  ('92690', 'Mission Viejo', 'CA', true, 'Mission Viejo'),
  ('92691', 'Mission Viejo', 'CA', true, 'Mission Viejo'),
  ('92692', 'Mission Viejo', 'CA', true, 'Mission Viejo'),
  ('92693', 'San Juan Capistrano', 'CA', true, 'San Juan Capistrano'),
  ('92694', 'Ladera Ranch', 'CA', true, 'Ladera Ranch'),
  ('92697', 'Irvine', 'CA', true, 'Irvine'),
  ('92698', 'Aliso Viejo', 'CA', true, 'Aliso Viejo'),
  ('92701', 'Santa Ana', 'CA', true, 'Santa Ana'),
  ('92702', 'Santa Ana', 'CA', true, 'Santa Ana'),
  ('92703', 'Santa Ana', 'CA', true, 'Santa Ana'),
  ('92704', 'Santa Ana', 'CA', true, 'Santa Ana'),
  ('92705', 'Santa Ana', 'CA', true, 'Santa Ana'),
  ('92706', 'Santa Ana', 'CA', true, 'Santa Ana'),
  ('92707', 'Santa Ana', 'CA', true, 'Santa Ana'),
  ('92708', 'Fountain Valley', 'CA', true, 'Fountain Valley'),
  ('92711', 'Santa Ana', 'CA', true, 'Santa Ana'),
  ('92712', 'Santa Ana', 'CA', true, 'Santa Ana'),
  ('92728', 'Fountain Valley', 'CA', true, 'Fountain Valley'),
  ('92735', 'Santa Ana', 'CA', true, 'Santa Ana'),
  ('92780', 'Tustin', 'CA', true, 'Tustin'),
  ('92781', 'Tustin', 'CA', true, 'Tustin'),
  ('92782', 'Tustin', 'CA', true, 'Tustin'),
  ('92799', 'Santa Ana', 'CA', true, 'Santa Ana'),
  ('92801', 'Anaheim', 'CA', true, 'Anaheim'),
  ('92802', 'Anaheim', 'CA', true, 'Anaheim'),
  ('92803', 'Anaheim', 'CA', true, 'Anaheim'),
  ('92804', 'Anaheim', 'CA', true, 'Anaheim'),
  ('92805', 'Anaheim', 'CA', true, 'Anaheim'),
  ('92806', 'Anaheim', 'CA', true, 'Anaheim'),
  ('92807', 'Anaheim', 'CA', true, 'Anaheim'),
  ('92808', 'Anaheim', 'CA', true, 'Anaheim'),
  ('92809', 'Anaheim', 'CA', true, 'Anaheim'),
  ('92811', 'Atwood', 'CA', true, 'Atwood'),
  ('92812', 'Anaheim', 'CA', true, 'Anaheim'),
  ('92814', 'Anaheim', 'CA', true, 'Anaheim'),
  ('92815', 'Anaheim', 'CA', true, 'Anaheim'),
  ('92816', 'Anaheim', 'CA', true, 'Anaheim'),
  ('92817', 'Anaheim', 'CA', true, 'Anaheim'),
  ('92821', 'Brea', 'CA', true, 'Brea'),
  ('92822', 'Brea', 'CA', true, 'Brea'),
  ('92823', 'Brea', 'CA', true, 'Brea'),
  ('92825', 'Anaheim', 'CA', true, 'Anaheim'),
  ('92831', 'Fullerton', 'CA', true, 'Fullerton'),
  ('92832', 'Fullerton', 'CA', true, 'Fullerton'),
  ('92833', 'Fullerton', 'CA', true, 'Fullerton'),
  ('92834', 'Fullerton', 'CA', true, 'Fullerton'),
  ('92835', 'Fullerton', 'CA', true, 'Fullerton'),
  ('92836', 'Fullerton', 'CA', true, 'Fullerton'),
  ('92837', 'Fullerton', 'CA', true, 'Fullerton'),
  ('92838', 'Fullerton', 'CA', true, 'Fullerton'),
  ('92840', 'Garden Grove', 'CA', true, 'Garden Grove'),
  ('92841', 'Garden Grove', 'CA', true, 'Garden Grove'),
  ('92842', 'Garden Grove', 'CA', true, 'Garden Grove'),
  ('92843', 'Garden Grove', 'CA', true, 'Garden Grove'),
  ('92844', 'Garden Grove', 'CA', true, 'Garden Grove'),
  ('92845', 'Garden Grove', 'CA', true, 'Garden Grove'),
  ('92846', 'Garden Grove', 'CA', true, 'Garden Grove'),
  ('92850', 'Anaheim', 'CA', true, 'Anaheim'),
  ('92856', 'Orange', 'CA', true, 'Orange'),
  ('92857', 'Orange', 'CA', true, 'Orange'),
  ('92859', 'Orange', 'CA', true, 'Orange'),
  ('92861', 'Villa Park', 'CA', true, 'Villa Park'),
  ('92862', 'Orange', 'CA', true, 'Orange'),
  ('92863', 'Orange', 'CA', true, 'Orange'),
  ('92864', 'Orange', 'CA', true, 'Orange'),
  ('92865', 'Orange', 'CA', true, 'Orange'),
  ('92866', 'Orange', 'CA', true, 'Orange'),
  ('92867', 'Orange', 'CA', true, 'Orange'),
  ('92868', 'Orange', 'CA', true, 'Orange'),
  ('92869', 'Orange', 'CA', true, 'Orange'),
  ('92870', 'Placentia', 'CA', true, 'Placentia'),
  ('92871', 'Placentia', 'CA', true, 'Placentia'),
  ('92885', 'Yorba Linda', 'CA', true, 'Yorba Linda'),
  ('92886', 'Yorba Linda', 'CA', true, 'Yorba Linda'),
  ('92887', 'Yorba Linda', 'CA', true, 'Yorba Linda'),
  ('92899', 'Anaheim', 'CA', true, 'Anaheim'),
  -- Riverside County, CA,
  ('91752', 'Mira Loma', 'CA', true, 'Mira Loma'),
  ('92201', 'Indio', 'CA', true, 'Indio'),
  ('92202', 'Indio', 'CA', true, 'Indio'),
  ('92203', 'Indio', 'CA', true, 'Indio'),
  ('92210', 'Indian Wells', 'CA', true, 'Indian Wells'),
  ('92211', 'Palm Desert', 'CA', true, 'Palm Desert'),
  ('92220', 'Banning', 'CA', true, 'Banning'),
  ('92223', 'Beaumont', 'CA', true, 'Beaumont'),
  ('92225', 'Blythe', 'CA', true, 'Blythe'),
  ('92226', 'Blythe', 'CA', true, 'Blythe'),
  ('92230', 'Cabazon', 'CA', true, 'Cabazon'),
  ('92234', 'Cathedral City', 'CA', true, 'Cathedral City'),
  ('92235', 'Cathedral City', 'CA', true, 'Cathedral City'),
  ('92236', 'Coachella', 'CA', true, 'Coachella'),
  ('92239', 'Desert Center', 'CA', true, 'Desert Center'),
  ('92240', 'Desert Hot Springs', 'CA', true, 'Desert Hot Springs'),
  ('92241', 'Desert Hot Springs', 'CA', true, 'Desert Hot Springs'),
  ('92247', 'La Quinta', 'CA', true, 'La Quinta'),
  ('92248', 'La Quinta', 'CA', true, 'La Quinta'),
  ('92253', 'La Quinta', 'CA', true, 'La Quinta'),
  ('92254', 'Mecca', 'CA', true, 'Mecca'),
  ('92255', 'Palm Desert', 'CA', true, 'Palm Desert'),
  ('92258', 'North Palm Springs', 'CA', true, 'North Palm Springs'),
  ('92260', 'Palm Desert', 'CA', true, 'Palm Desert'),
  ('92261', 'Palm Desert', 'CA', true, 'Palm Desert'),
  ('92262', 'Palm Springs', 'CA', true, 'Palm Springs'),
  ('92263', 'Palm Springs', 'CA', true, 'Palm Springs'),
  ('92264', 'Palm Springs', 'CA', true, 'Palm Springs'),
  ('92270', 'Rancho Mirage', 'CA', true, 'Rancho Mirage'),
  ('92274', 'Thermal', 'CA', true, 'Thermal'),
  ('92276', 'Thousand Palms', 'CA', true, 'Thousand Palms'),
  ('92282', 'Whitewater', 'CA', true, 'Whitewater'),
  ('92320', 'Calimesa', 'CA', true, 'Calimesa'),
  ('92501', 'Riverside', 'CA', true, 'Riverside'),
  ('92502', 'Riverside', 'CA', true, 'Riverside'),
  ('92503', 'Riverside', 'CA', true, 'Riverside'),
  ('92504', 'Riverside', 'CA', true, 'Riverside'),
  ('92505', 'Riverside', 'CA', true, 'Riverside'),
  ('92506', 'Riverside', 'CA', true, 'Riverside'),
  ('92507', 'Riverside', 'CA', true, 'Riverside'),
  ('92508', 'Riverside', 'CA', true, 'Riverside'),
  ('92509', 'Jurupa Valley', 'CA', true, 'Jurupa Valley'),
  ('92513', 'Riverside', 'CA', true, 'Riverside'),
  ('92514', 'Riverside', 'CA', true, 'Riverside'),
  ('92516', 'Riverside', 'CA', true, 'Riverside'),
  ('92517', 'Riverside', 'CA', true, 'Riverside'),
  ('92518', 'March Air Reserve Base', 'CA', true, 'March Air Reserve Base'),
  ('92519', 'Riverside', 'CA', true, 'Riverside'),
  ('92521', 'Riverside', 'CA', true, 'Riverside'),
  ('92522', 'Riverside', 'CA', true, 'Riverside'),
  ('92530', 'Lake Elsinore', 'CA', true, 'Lake Elsinore'),
  ('92531', 'Lake Elsinore', 'CA', true, 'Lake Elsinore'),
  ('92532', 'Lake Elsinore', 'CA', true, 'Lake Elsinore'),
  ('92536', 'Aguanga', 'CA', true, 'Aguanga'),
  ('92539', 'Anza', 'CA', true, 'Anza'),
  ('92543', 'Hemet', 'CA', true, 'Hemet'),
  ('92544', 'Hemet', 'CA', true, 'Hemet'),
  ('92545', 'Hemet', 'CA', true, 'Hemet'),
  ('92546', 'Hemet', 'CA', true, 'Hemet'),
  ('92548', 'Homeland', 'CA', true, 'Homeland'),
  ('92549', 'Idyllwild', 'CA', true, 'Idyllwild'),
  ('92551', 'Moreno Valley', 'CA', true, 'Moreno Valley'),
  ('92552', 'Moreno Valley', 'CA', true, 'Moreno Valley'),
  ('92553', 'Moreno Valley', 'CA', true, 'Moreno Valley'),
  ('92554', 'Moreno Valley', 'CA', true, 'Moreno Valley'),
  ('92555', 'Moreno Valley', 'CA', true, 'Moreno Valley'),
  ('92556', 'Moreno Valley', 'CA', true, 'Moreno Valley'),
  ('92557', 'Moreno Valley', 'CA', true, 'Moreno Valley'),
  ('92561', 'Mountain Center', 'CA', true, 'Mountain Center'),
  ('92562', 'Murrieta', 'CA', true, 'Murrieta'),
  ('92563', 'Murrieta', 'CA', true, 'Murrieta'),
  ('92564', 'Murrieta', 'CA', true, 'Murrieta'),
  ('92567', 'Nuevo', 'CA', true, 'Nuevo'),
  ('92570', 'Perris', 'CA', true, 'Perris'),
  ('92571', 'Perris', 'CA', true, 'Perris'),
  ('92572', 'Perris', 'CA', true, 'Perris'),
  ('92581', 'San Jacinto', 'CA', true, 'San Jacinto'),
  ('92582', 'San Jacinto', 'CA', true, 'San Jacinto'),
  ('92583', 'San Jacinto', 'CA', true, 'San Jacinto'),
  ('92584', 'Menifee', 'CA', true, 'Menifee'),
  ('92585', 'Menifee', 'CA', true, 'Menifee'),
  ('92586', 'Menifee', 'CA', true, 'Menifee'),
  ('92587', 'Menifee', 'CA', true, 'Menifee'),
  ('92589', 'Temecula', 'CA', true, 'Temecula'),
  ('92590', 'Temecula', 'CA', true, 'Temecula'),
  ('92591', 'Temecula', 'CA', true, 'Temecula'),
  ('92592', 'Temecula', 'CA', true, 'Temecula'),
  ('92593', 'Temecula', 'CA', true, 'Temecula'),
  ('92595', 'Wildomar', 'CA', true, 'Wildomar'),
  ('92596', 'Winchester', 'CA', true, 'Winchester'),
  ('92599', 'Perris', 'CA', true, 'Perris'),
  ('92860', 'Norco', 'CA', true, 'Norco'),
  ('92877', 'Corona', 'CA', true, 'Corona'),
  ('92878', 'Corona', 'CA', true, 'Corona'),
  ('92879', 'Corona', 'CA', true, 'Corona'),
  ('92880', 'Corona', 'CA', true, 'Corona'),
  ('92881', 'Corona', 'CA', true, 'Corona'),
  ('92882', 'Corona', 'CA', true, 'Corona'),
  ('92883', 'Corona', 'CA', true, 'Corona'),
  -- San Diego County, CA,
  ('91901', 'Alpine', 'CA', true, 'Alpine'),
  ('91902', 'Bonita', 'CA', true, 'Bonita'),
  ('91903', 'Alpine', 'CA', true, 'Alpine'),
  ('91905', 'Boulevard', 'CA', true, 'Boulevard'),
  ('91906', 'Campo', 'CA', true, 'Campo'),
  ('91908', 'Bonita', 'CA', true, 'Bonita'),
  ('91909', 'Chula Vista', 'CA', true, 'Chula Vista'),
  ('91910', 'Chula Vista', 'CA', true, 'Chula Vista'),
  ('91911', 'Chula Vista', 'CA', true, 'Chula Vista'),
  ('91912', 'Chula Vista', 'CA', true, 'Chula Vista'),
  ('91913', 'Chula Vista', 'CA', true, 'Chula Vista'),
  ('91914', 'Chula Vista', 'CA', true, 'Chula Vista'),
  ('91915', 'Chula Vista', 'CA', true, 'Chula Vista'),
  ('91916', 'Descanso', 'CA', true, 'Descanso'),
  ('91917', 'Dulzura', 'CA', true, 'Dulzura'),
  ('91921', 'Chula Vista', 'CA', true, 'Chula Vista'),
  ('91931', 'Guatay', 'CA', true, 'Guatay'),
  ('91932', 'Imperial Beach', 'CA', true, 'Imperial Beach'),
  ('91933', 'Imperial Beach', 'CA', true, 'Imperial Beach'),
  ('91934', 'Jacumba', 'CA', true, 'Jacumba'),
  ('91935', 'Jamul', 'CA', true, 'Jamul'),
  ('91941', 'La Mesa', 'CA', true, 'La Mesa'),
  ('91942', 'La Mesa', 'CA', true, 'La Mesa'),
  ('91943', 'La Mesa', 'CA', true, 'La Mesa'),
  ('91944', 'La Mesa', 'CA', true, 'La Mesa'),
  ('91945', 'Lemon Grove', 'CA', true, 'Lemon Grove'),
  ('91946', 'Lemon Grove', 'CA', true, 'Lemon Grove'),
  ('91948', 'Mount Laguna', 'CA', true, 'Mount Laguna'),
  ('91950', 'National City', 'CA', true, 'National City'),
  ('91951', 'National City', 'CA', true, 'National City'),
  ('91962', 'Pine Valley', 'CA', true, 'Pine Valley'),
  ('91963', 'Potrero', 'CA', true, 'Potrero'),
  ('91976', 'Spring Valley', 'CA', true, 'Spring Valley'),
  ('91977', 'Spring Valley', 'CA', true, 'Spring Valley'),
  ('91978', 'Spring Valley', 'CA', true, 'Spring Valley'),
  ('91979', 'Spring Valley', 'CA', true, 'Spring Valley'),
  ('91980', 'Tecate', 'CA', true, 'Tecate'),
  ('91987', 'Tecate', 'CA', true, 'Tecate'),
  ('92003', 'Bonsall', 'CA', true, 'Bonsall'),
  ('92004', 'Borrego Springs', 'CA', true, 'Borrego Springs'),
  ('92007', 'Cardiff By The Sea', 'CA', true, 'Cardiff By The Sea'),
  ('92008', 'Carlsbad', 'CA', true, 'Carlsbad'),
  ('92009', 'Carlsbad', 'CA', true, 'Carlsbad'),
  ('92010', 'Carlsbad', 'CA', true, 'Carlsbad'),
  ('92011', 'Carlsbad', 'CA', true, 'Carlsbad'),
  ('92013', 'Carlsbad', 'CA', true, 'Carlsbad'),
  ('92014', 'Del Mar', 'CA', true, 'Del Mar'),
  ('92018', 'Carlsbad', 'CA', true, 'Carlsbad'),
  ('92019', 'El Cajon', 'CA', true, 'El Cajon'),
  ('92020', 'El Cajon', 'CA', true, 'El Cajon'),
  ('92021', 'El Cajon', 'CA', true, 'El Cajon'),
  ('92022', 'El Cajon', 'CA', true, 'El Cajon'),
  ('92023', 'Encinitas', 'CA', true, 'Encinitas'),
  ('92024', 'Encinitas', 'CA', true, 'Encinitas'),
  ('92025', 'Escondido', 'CA', true, 'Escondido'),
  ('92026', 'Escondido', 'CA', true, 'Escondido'),
  ('92027', 'Escondido', 'CA', true, 'Escondido'),
  ('92028', 'Fallbrook', 'CA', true, 'Fallbrook'),
  ('92029', 'Escondido', 'CA', true, 'Escondido'),
  ('92030', 'Escondido', 'CA', true, 'Escondido'),
  ('92033', 'Escondido', 'CA', true, 'Escondido'),
  ('92036', 'Julian', 'CA', true, 'Julian'),
  ('92037', 'La Jolla', 'CA', true, 'La Jolla'),
  ('92038', 'La Jolla', 'CA', true, 'La Jolla'),
  ('92039', 'La Jolla', 'CA', true, 'La Jolla'),
  ('92040', 'Lakeside', 'CA', true, 'Lakeside'),
  ('92046', 'Escondido', 'CA', true, 'Escondido'),
  ('92049', 'Oceanside', 'CA', true, 'Oceanside'),
  ('92051', 'Oceanside', 'CA', true, 'Oceanside'),
  ('92052', 'Oceanside', 'CA', true, 'Oceanside'),
  ('92054', 'Oceanside', 'CA', true, 'Oceanside'),
  ('92055', 'Camp Pendleton', 'CA', true, 'Camp Pendleton'),
  ('92056', 'Oceanside', 'CA', true, 'Oceanside'),
  ('92057', 'Oceanside', 'CA', true, 'Oceanside'),
  ('92058', 'Oceanside', 'CA', true, 'Oceanside'),
  ('92059', 'Pala', 'CA', true, 'Pala'),
  ('92060', 'Palomar Mountain', 'CA', true, 'Palomar Mountain'),
  ('92061', 'Pauma Valley', 'CA', true, 'Pauma Valley'),
  ('92064', 'Poway', 'CA', true, 'Poway'),
  ('92065', 'Ramona', 'CA', true, 'Ramona'),
  ('92066', 'Ranchita', 'CA', true, 'Ranchita'),
  ('92067', 'Rancho Santa Fe', 'CA', true, 'Rancho Santa Fe'),
  ('92068', 'San Luis Rey', 'CA', true, 'San Luis Rey'),
  ('92069', 'San Marcos', 'CA', true, 'San Marcos'),
  ('92070', 'Santa Ysabel', 'CA', true, 'Santa Ysabel'),
  ('92071', 'Santee', 'CA', true, 'Santee'),
  ('92072', 'Santee', 'CA', true, 'Santee'),
  ('92074', 'Poway', 'CA', true, 'Poway'),
  ('92075', 'Solana Beach', 'CA', true, 'Solana Beach'),
  ('92078', 'San Marcos', 'CA', true, 'San Marcos'),
  ('92079', 'San Marcos', 'CA', true, 'San Marcos'),
  ('92081', 'Vista', 'CA', true, 'Vista'),
  ('92082', 'Valley Center', 'CA', true, 'Valley Center'),
  ('92083', 'Vista', 'CA', true, 'Vista'),
  ('92084', 'Vista', 'CA', true, 'Vista'),
  ('92085', 'Vista', 'CA', true, 'Vista'),
  ('92086', 'Warner Springs', 'CA', true, 'Warner Springs'),
  ('92088', 'Fallbrook', 'CA', true, 'Fallbrook'),
  ('92091', 'Rancho Santa Fe', 'CA', true, 'Rancho Santa Fe'),
  ('92092', 'La Jolla', 'CA', true, 'La Jolla'),
  ('92093', 'La Jolla', 'CA', true, 'La Jolla'),
  ('92096', 'San Marcos', 'CA', true, 'San Marcos'),
  ('92101', 'San Diego', 'CA', true, 'San Diego'),
  ('92102', 'San Diego', 'CA', true, 'San Diego'),
  ('92103', 'San Diego', 'CA', true, 'San Diego'),
  ('92104', 'San Diego', 'CA', true, 'San Diego'),
  ('92105', 'San Diego', 'CA', true, 'San Diego'),
  ('92106', 'San Diego', 'CA', true, 'San Diego'),
  ('92107', 'San Diego', 'CA', true, 'San Diego'),
  ('92108', 'San Diego', 'CA', true, 'San Diego'),
  ('92109', 'San Diego', 'CA', true, 'San Diego'),
  ('92110', 'San Diego', 'CA', true, 'San Diego'),
  ('92111', 'San Diego', 'CA', true, 'San Diego'),
  ('92112', 'San Diego', 'CA', true, 'San Diego'),
  ('92113', 'San Diego', 'CA', true, 'San Diego'),
  ('92114', 'San Diego', 'CA', true, 'San Diego'),
  ('92115', 'San Diego', 'CA', true, 'San Diego'),
  ('92116', 'San Diego', 'CA', true, 'San Diego'),
  ('92117', 'San Diego', 'CA', true, 'San Diego'),
  ('92118', 'Coronado', 'CA', true, 'Coronado'),
  ('92119', 'San Diego', 'CA', true, 'San Diego'),
  ('92120', 'San Diego', 'CA', true, 'San Diego'),
  ('92121', 'San Diego', 'CA', true, 'San Diego'),
  ('92122', 'San Diego', 'CA', true, 'San Diego'),
  ('92123', 'San Diego', 'CA', true, 'San Diego'),
  ('92124', 'San Diego', 'CA', true, 'San Diego'),
  ('92126', 'San Diego', 'CA', true, 'San Diego'),
  ('92127', 'San Diego', 'CA', true, 'San Diego'),
  ('92128', 'San Diego', 'CA', true, 'San Diego'),
  ('92129', 'San Diego', 'CA', true, 'San Diego'),
  ('92130', 'San Diego', 'CA', true, 'San Diego'),
  ('92131', 'San Diego', 'CA', true, 'San Diego'),
  ('92132', 'San Diego', 'CA', true, 'San Diego'),
  ('92134', 'San Diego', 'CA', true, 'San Diego'),
  ('92135', 'San Diego', 'CA', true, 'San Diego'),
  ('92136', 'San Diego', 'CA', true, 'San Diego'),
  ('92137', 'San Diego', 'CA', true, 'San Diego'),
  ('92138', 'San Diego', 'CA', true, 'San Diego'),
  ('92139', 'San Diego', 'CA', true, 'San Diego'),
  ('92140', 'San Diego', 'CA', true, 'San Diego'),
  ('92142', 'San Diego', 'CA', true, 'San Diego'),
  ('92143', 'San Ysidro', 'CA', true, 'San Ysidro'),
  ('92145', 'San Diego', 'CA', true, 'San Diego'),
  ('92147', 'San Diego', 'CA', true, 'San Diego'),
  ('92149', 'San Diego', 'CA', true, 'San Diego'),
  ('92150', 'San Diego', 'CA', true, 'San Diego'),
  ('92152', 'San Diego', 'CA', true, 'San Diego'),
  ('92153', 'San Diego', 'CA', true, 'San Diego'),
  ('92154', 'San Diego', 'CA', true, 'San Diego'),
  ('92155', 'San Diego', 'CA', true, 'San Diego'),
  ('92158', 'San Diego', 'CA', true, 'San Diego'),
  ('92159', 'San Diego', 'CA', true, 'San Diego'),
  ('92160', 'San Diego', 'CA', true, 'San Diego'),
  ('92161', 'San Diego', 'CA', true, 'San Diego'),
  ('92163', 'San Diego', 'CA', true, 'San Diego'),
  ('92165', 'San Diego', 'CA', true, 'San Diego'),
  ('92166', 'San Diego', 'CA', true, 'San Diego'),
  ('92167', 'San Diego', 'CA', true, 'San Diego'),
  ('92168', 'San Diego', 'CA', true, 'San Diego'),
  ('92169', 'San Diego', 'CA', true, 'San Diego'),
  ('92170', 'San Diego', 'CA', true, 'San Diego'),
  ('92171', 'San Diego', 'CA', true, 'San Diego'),
  ('92172', 'San Diego', 'CA', true, 'San Diego'),
  ('92173', 'San Ysidro', 'CA', true, 'San Ysidro'),
  ('92174', 'San Diego', 'CA', true, 'San Diego'),
  ('92175', 'San Diego', 'CA', true, 'San Diego'),
  ('92176', 'San Diego', 'CA', true, 'San Diego'),
  ('92177', 'San Diego', 'CA', true, 'San Diego'),
  ('92178', 'Coronado', 'CA', true, 'Coronado'),
  ('92179', 'San Diego', 'CA', true, 'San Diego'),
  ('92182', 'San Diego', 'CA', true, 'San Diego'),
  ('92186', 'San Diego', 'CA', true, 'San Diego'),
  ('92187', 'San Diego', 'CA', true, 'San Diego'),
  ('92191', 'San Diego', 'CA', true, 'San Diego'),
  ('92192', 'San Diego', 'CA', true, 'San Diego'),
  ('92193', 'San Diego', 'CA', true, 'San Diego'),
  ('92195', 'San Diego', 'CA', true, 'San Diego'),
  ('92196', 'San Diego', 'CA', true, 'San Diego'),
  ('92197', 'San Diego', 'CA', true, 'San Diego'),
  ('92198', 'San Diego', 'CA', true, 'San Diego'),
  ('92199', 'San Diego', 'CA', true, 'San Diego'),
  -- Los Angeles County, CA,
  ('90001', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90002', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90003', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90004', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90005', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90006', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90007', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90008', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90009', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90010', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90011', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90012', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90013', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90014', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90015', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90016', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90017', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90018', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90019', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90020', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90021', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90022', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90023', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90024', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90025', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90026', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90027', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90028', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90029', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90030', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90031', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90032', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90033', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90034', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90035', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90036', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90037', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90038', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90039', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90040', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90041', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90042', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90043', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90044', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90045', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90046', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90047', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90048', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90049', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90050', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90051', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90052', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90053', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90054', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90055', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90056', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90057', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90058', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90059', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90060', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90061', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90062', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90063', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90064', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90065', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90066', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90067', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90068', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90069', 'West Hollywood', 'CA', true, 'West Hollywood'),
  ('90070', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90071', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90072', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90073', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90074', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90075', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90076', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90077', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90078', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90079', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90080', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90081', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90082', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90083', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90084', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90086', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90087', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90088', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90089', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90090', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90091', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90093', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90094', 'Playa Vista', 'CA', true, 'Playa Vista'),
  ('90095', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90096', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90099', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90134', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90189', 'Los Angeles', 'CA', true, 'Los Angeles'),
  ('90201', 'Bell Gardens', 'CA', true, 'Bell Gardens'),
  ('90202', 'Bell', 'CA', true, 'Bell'),
  ('90209', 'Beverly Hills', 'CA', true, 'Beverly Hills'),
  ('90210', 'Beverly Hills', 'CA', true, 'Beverly Hills'),
  ('90211', 'Beverly Hills', 'CA', true, 'Beverly Hills'),
  ('90212', 'Beverly Hills', 'CA', true, 'Beverly Hills'),
  ('90213', 'Beverly Hills', 'CA', true, 'Beverly Hills'),
  ('90220', 'Compton', 'CA', true, 'Compton'),
  ('90221', 'Compton', 'CA', true, 'Compton'),
  ('90222', 'Compton', 'CA', true, 'Compton'),
  ('90223', 'Compton', 'CA', true, 'Compton'),
  ('90224', 'Compton', 'CA', true, 'Compton'),
  ('90230', 'Culver City', 'CA', true, 'Culver City'),
  ('90231', 'Culver City', 'CA', true, 'Culver City'),
  ('90232', 'Culver City', 'CA', true, 'Culver City'),
  ('90233', 'Culver City', 'CA', true, 'Culver City'),
  ('90239', 'Downey', 'CA', true, 'Downey'),
  ('90240', 'Downey', 'CA', true, 'Downey'),
  ('90241', 'Downey', 'CA', true, 'Downey'),
  ('90242', 'Downey', 'CA', true, 'Downey'),
  ('90245', 'El Segundo', 'CA', true, 'El Segundo'),
  ('90247', 'Gardena', 'CA', true, 'Gardena'),
  ('90248', 'Gardena', 'CA', true, 'Gardena'),
  ('90249', 'Gardena', 'CA', true, 'Gardena'),
  ('90250', 'Hawthorne', 'CA', true, 'Hawthorne'),
  ('90251', 'Hawthorne', 'CA', true, 'Hawthorne'),
  ('90254', 'Hermosa Beach', 'CA', true, 'Hermosa Beach'),
  ('90255', 'Huntington Park', 'CA', true, 'Huntington Park'),
  ('90260', 'Lawndale', 'CA', true, 'Lawndale'),
  ('90261', 'Lawndale', 'CA', true, 'Lawndale'),
  ('90262', 'Lynwood', 'CA', true, 'Lynwood'),
  ('90263', 'Malibu', 'CA', true, 'Malibu'),
  ('90264', 'Malibu', 'CA', true, 'Malibu'),
  ('90265', 'Malibu', 'CA', true, 'Malibu'),
  ('90266', 'Manhattan Beach', 'CA', true, 'Manhattan Beach'),
  ('90267', 'Manhattan Beach', 'CA', true, 'Manhattan Beach'),
  ('90270', 'Maywood', 'CA', true, 'Maywood'),
  ('90272', 'Pacific Palisades', 'CA', true, 'Pacific Palisades'),
  ('90274', 'Palos Verdes Peninsula', 'CA', true, 'Palos Verdes Peninsula'),
  ('90275', 'Rancho Palos Verdes', 'CA', true, 'Rancho Palos Verdes'),
  ('90277', 'Redondo Beach', 'CA', true, 'Redondo Beach'),
  ('90278', 'Redondo Beach', 'CA', true, 'Redondo Beach'),
  ('90280', 'South Gate', 'CA', true, 'South Gate'),
  ('90290', 'Topanga', 'CA', true, 'Topanga'),
  ('90291', 'Venice', 'CA', true, 'Venice'),
  ('90292', 'Marina Del Rey', 'CA', true, 'Marina Del Rey'),
  ('90293', 'Playa Del Rey', 'CA', true, 'Playa Del Rey'),
  ('90294', 'Venice', 'CA', true, 'Venice'),
  ('90295', 'Marina Del Rey', 'CA', true, 'Marina Del Rey'),
  ('90296', 'Playa Del Rey', 'CA', true, 'Playa Del Rey'),
  ('90301', 'Inglewood', 'CA', true, 'Inglewood'),
  ('90302', 'Inglewood', 'CA', true, 'Inglewood'),
  ('90303', 'Inglewood', 'CA', true, 'Inglewood'),
  ('90304', 'Inglewood', 'CA', true, 'Inglewood'),
  ('90305', 'Inglewood', 'CA', true, 'Inglewood'),
  ('90306', 'Inglewood', 'CA', true, 'Inglewood'),
  ('90307', 'Inglewood', 'CA', true, 'Inglewood'),
  ('90308', 'Inglewood', 'CA', true, 'Inglewood'),
  ('90309', 'Inglewood', 'CA', true, 'Inglewood'),
  ('90310', 'Inglewood', 'CA', true, 'Inglewood'),
  ('90311', 'Inglewood', 'CA', true, 'Inglewood'),
  ('90312', 'Inglewood', 'CA', true, 'Inglewood'),
  ('90401', 'Santa Monica', 'CA', true, 'Santa Monica'),
  ('90402', 'Santa Monica', 'CA', true, 'Santa Monica'),
  ('90403', 'Santa Monica', 'CA', true, 'Santa Monica'),
  ('90404', 'Santa Monica', 'CA', true, 'Santa Monica'),
  ('90405', 'Santa Monica', 'CA', true, 'Santa Monica'),
  ('90406', 'Santa Monica', 'CA', true, 'Santa Monica'),
  ('90407', 'Santa Monica', 'CA', true, 'Santa Monica'),
  ('90408', 'Santa Monica', 'CA', true, 'Santa Monica'),
  ('90409', 'Santa Monica', 'CA', true, 'Santa Monica'),
  ('90410', 'Santa Monica', 'CA', true, 'Santa Monica'),
  ('90411', 'Santa Monica', 'CA', true, 'Santa Monica'),
  ('90501', 'Torrance', 'CA', true, 'Torrance'),
  ('90502', 'Torrance', 'CA', true, 'Torrance'),
  ('90503', 'Torrance', 'CA', true, 'Torrance'),
  ('90504', 'Torrance', 'CA', true, 'Torrance'),
  ('90505', 'Torrance', 'CA', true, 'Torrance'),
  ('90506', 'Torrance', 'CA', true, 'Torrance'),
  ('90507', 'Torrance', 'CA', true, 'Torrance'),
  ('90508', 'Torrance', 'CA', true, 'Torrance'),
  ('90509', 'Torrance', 'CA', true, 'Torrance'),
  ('90510', 'Torrance', 'CA', true, 'Torrance'),
  ('90601', 'Whittier', 'CA', true, 'Whittier'),
  ('90602', 'Whittier', 'CA', true, 'Whittier'),
  ('90603', 'Whittier', 'CA', true, 'Whittier'),
  ('90604', 'Whittier', 'CA', true, 'Whittier'),
  ('90605', 'Whittier', 'CA', true, 'Whittier'),
  ('90606', 'Whittier', 'CA', true, 'Whittier'),
  ('90607', 'Whittier', 'CA', true, 'Whittier'),
  ('90608', 'Whittier', 'CA', true, 'Whittier'),
  ('90609', 'Whittier', 'CA', true, 'Whittier'),
  ('90610', 'Whittier', 'CA', true, 'Whittier'),
  ('90637', 'La Mirada', 'CA', true, 'La Mirada'),
  ('90638', 'La Mirada', 'CA', true, 'La Mirada'),
  ('90639', 'La Mirada', 'CA', true, 'La Mirada'),
  ('90640', 'Montebello', 'CA', true, 'Montebello'),
  ('90650', 'Norwalk', 'CA', true, 'Norwalk'),
  ('90651', 'Norwalk', 'CA', true, 'Norwalk'),
  ('90652', 'Norwalk', 'CA', true, 'Norwalk'),
  ('90660', 'Pico Rivera', 'CA', true, 'Pico Rivera'),
  ('90661', 'Pico Rivera', 'CA', true, 'Pico Rivera'),
  ('90662', 'Pico Rivera', 'CA', true, 'Pico Rivera'),
  ('90670', 'Santa Fe Springs', 'CA', true, 'Santa Fe Springs'),
  ('90671', 'Santa Fe Springs', 'CA', true, 'Santa Fe Springs'),
  ('90701', 'Artesia', 'CA', true, 'Artesia'),
  ('90702', 'Artesia', 'CA', true, 'Artesia'),
  ('90703', 'Cerritos', 'CA', true, 'Cerritos'),
  ('90704', 'Avalon', 'CA', true, 'Avalon'),
  ('90706', 'Bellflower', 'CA', true, 'Bellflower'),
  ('90707', 'Bellflower', 'CA', true, 'Bellflower'),
  ('90710', 'Harbor City', 'CA', true, 'Harbor City'),
  ('90711', 'Lakewood', 'CA', true, 'Lakewood'),
  ('90712', 'Lakewood', 'CA', true, 'Lakewood'),
  ('90713', 'Lakewood', 'CA', true, 'Lakewood'),
  ('90714', 'Lakewood', 'CA', true, 'Lakewood'),
  ('90715', 'Lakewood', 'CA', true, 'Lakewood'),
  ('90716', 'Hawaiian Gardens', 'CA', true, 'Hawaiian Gardens'),
  ('90717', 'Lomita', 'CA', true, 'Lomita'),
  ('90723', 'Paramount', 'CA', true, 'Paramount'),
  ('90731', 'San Pedro', 'CA', true, 'San Pedro'),
  ('90732', 'San Pedro', 'CA', true, 'San Pedro'),
  ('90733', 'San Pedro', 'CA', true, 'San Pedro'),
  ('90734', 'San Pedro', 'CA', true, 'San Pedro'),
  ('90744', 'Wilmington', 'CA', true, 'Wilmington'),
  ('90745', 'Carson', 'CA', true, 'Carson'),
  ('90746', 'Carson', 'CA', true, 'Carson'),
  ('90747', 'Carson', 'CA', true, 'Carson'),
  ('90748', 'Wilmington', 'CA', true, 'Wilmington'),
  ('90749', 'Carson', 'CA', true, 'Carson'),
  ('90755', 'Signal Hill', 'CA', true, 'Signal Hill'),
  ('90801', 'Long Beach', 'CA', true, 'Long Beach'),
  ('90802', 'Long Beach', 'CA', true, 'Long Beach'),
  ('90803', 'Long Beach', 'CA', true, 'Long Beach'),
  ('90804', 'Long Beach', 'CA', true, 'Long Beach'),
  ('90805', 'Long Beach', 'CA', true, 'Long Beach'),
  ('90806', 'Long Beach', 'CA', true, 'Long Beach'),
  ('90807', 'Long Beach', 'CA', true, 'Long Beach'),
  ('90808', 'Long Beach', 'CA', true, 'Long Beach'),
  ('90809', 'Long Beach', 'CA', true, 'Long Beach'),
  ('90810', 'Long Beach', 'CA', true, 'Long Beach'),
  ('90813', 'Long Beach', 'CA', true, 'Long Beach'),
  ('90814', 'Long Beach', 'CA', true, 'Long Beach'),
  ('90815', 'Long Beach', 'CA', true, 'Long Beach'),
  ('90822', 'Long Beach', 'CA', true, 'Long Beach'),
  ('90831', 'Long Beach', 'CA', true, 'Long Beach'),
  ('90832', 'Long Beach', 'CA', true, 'Long Beach'),
  ('90833', 'Long Beach', 'CA', true, 'Long Beach'),
  ('90840', 'Long Beach', 'CA', true, 'Long Beach'),
  ('90842', 'Long Beach', 'CA', true, 'Long Beach'),
  ('90844', 'Long Beach', 'CA', true, 'Long Beach'),
  ('90846', 'Long Beach', 'CA', true, 'Long Beach'),
  ('90847', 'Long Beach', 'CA', true, 'Long Beach'),
  ('90848', 'Long Beach', 'CA', true, 'Long Beach'),
  ('90853', 'Long Beach', 'CA', true, 'Long Beach'),
  ('90895', 'Carson', 'CA', true, 'Carson'),
  ('91001', 'Altadena', 'CA', true, 'Altadena'),
  ('91003', 'Altadena', 'CA', true, 'Altadena'),
  ('91006', 'Arcadia', 'CA', true, 'Arcadia'),
  ('91007', 'Arcadia', 'CA', true, 'Arcadia'),
  ('91008', 'Duarte', 'CA', true, 'Duarte'),
  ('91009', 'Duarte', 'CA', true, 'Duarte'),
  ('91010', 'Duarte', 'CA', true, 'Duarte'),
  ('91011', 'La Canada Flintridge', 'CA', true, 'La Canada Flintridge'),
  ('91012', 'La Canada Flintridge', 'CA', true, 'La Canada Flintridge'),
  ('91016', 'Monrovia', 'CA', true, 'Monrovia'),
  ('91017', 'Monrovia', 'CA', true, 'Monrovia'),
  ('91020', 'Montrose', 'CA', true, 'Montrose'),
  ('91021', 'Montrose', 'CA', true, 'Montrose'),
  ('91023', 'Mount Wilson', 'CA', true, 'Mount Wilson'),
  ('91024', 'Sierra Madre', 'CA', true, 'Sierra Madre'),
  ('91025', 'Sierra Madre', 'CA', true, 'Sierra Madre'),
  ('91030', 'South Pasadena', 'CA', true, 'South Pasadena'),
  ('91031', 'South Pasadena', 'CA', true, 'South Pasadena'),
  ('91040', 'Sunland', 'CA', true, 'Sunland'),
  ('91041', 'Sunland', 'CA', true, 'Sunland'),
  ('91042', 'Tujunga', 'CA', true, 'Tujunga'),
  ('91043', 'Tujunga', 'CA', true, 'Tujunga'),
  ('91046', 'Verdugo City', 'CA', true, 'Verdugo City'),
  ('91066', 'Arcadia', 'CA', true, 'Arcadia'),
  ('91077', 'Arcadia', 'CA', true, 'Arcadia'),
  ('91101', 'Pasadena', 'CA', true, 'Pasadena'),
  ('91102', 'Pasadena', 'CA', true, 'Pasadena'),
  ('91103', 'Pasadena', 'CA', true, 'Pasadena'),
  ('91104', 'Pasadena', 'CA', true, 'Pasadena'),
  ('91105', 'Pasadena', 'CA', true, 'Pasadena'),
  ('91106', 'Pasadena', 'CA', true, 'Pasadena'),
  ('91107', 'Pasadena', 'CA', true, 'Pasadena'),
  ('91108', 'San Marino', 'CA', true, 'San Marino'),
  ('91109', 'Pasadena', 'CA', true, 'Pasadena'),
  ('91110', 'Pasadena', 'CA', true, 'Pasadena'),
  ('91114', 'Pasadena', 'CA', true, 'Pasadena'),
  ('91115', 'Pasadena', 'CA', true, 'Pasadena'),
  ('91116', 'Pasadena', 'CA', true, 'Pasadena'),
  ('91117', 'Pasadena', 'CA', true, 'Pasadena'),
  ('91118', 'San Marino', 'CA', true, 'San Marino'),
  ('91121', 'Pasadena', 'CA', true, 'Pasadena'),
  ('91123', 'Pasadena', 'CA', true, 'Pasadena'),
  ('91124', 'Pasadena', 'CA', true, 'Pasadena'),
  ('91125', 'Pasadena', 'CA', true, 'Pasadena'),
  ('91126', 'Pasadena', 'CA', true, 'Pasadena'),
  ('91129', 'Pasadena', 'CA', true, 'Pasadena'),
  ('91182', 'Pasadena', 'CA', true, 'Pasadena'),
  ('91184', 'Pasadena', 'CA', true, 'Pasadena'),
  ('91185', 'Pasadena', 'CA', true, 'Pasadena'),
  ('91188', 'Pasadena', 'CA', true, 'Pasadena'),
  ('91189', 'Pasadena', 'CA', true, 'Pasadena'),
  ('91199', 'Pasadena', 'CA', true, 'Pasadena'),
  ('91201', 'Glendale', 'CA', true, 'Glendale'),
  ('91202', 'Glendale', 'CA', true, 'Glendale'),
  ('91203', 'Glendale', 'CA', true, 'Glendale'),
  ('91204', 'Glendale', 'CA', true, 'Glendale'),
  ('91205', 'Glendale', 'CA', true, 'Glendale'),
  ('91206', 'Glendale', 'CA', true, 'Glendale'),
  ('91207', 'Glendale', 'CA', true, 'Glendale'),
  ('91208', 'Glendale', 'CA', true, 'Glendale'),
  ('91209', 'Glendale', 'CA', true, 'Glendale'),
  ('91210', 'Glendale', 'CA', true, 'Glendale'),
  ('91214', 'La Crescenta', 'CA', true, 'La Crescenta'),
  ('91221', 'Glendale', 'CA', true, 'Glendale'),
  ('91222', 'Glendale', 'CA', true, 'Glendale'),
  ('91224', 'La Crescenta', 'CA', true, 'La Crescenta'),
  ('91225', 'Glendale', 'CA', true, 'Glendale'),
  ('91226', 'Glendale', 'CA', true, 'Glendale'),
  ('91301', 'Agoura Hills', 'CA', true, 'Agoura Hills'),
  ('91302', 'Calabasas', 'CA', true, 'Calabasas'),
  ('91303', 'Canoga Park', 'CA', true, 'Canoga Park'),
  ('91304', 'Canoga Park', 'CA', true, 'Canoga Park'),
  ('91305', 'Canoga Park', 'CA', true, 'Canoga Park'),
  ('91306', 'Winnetka', 'CA', true, 'Winnetka'),
  ('91307', 'West Hills', 'CA', true, 'West Hills'),
  ('91308', 'West Hills', 'CA', true, 'West Hills'),
  ('91309', 'Canoga Park', 'CA', true, 'Canoga Park'),
  ('91310', 'Castaic', 'CA', true, 'Castaic'),
  ('91311', 'Chatsworth', 'CA', true, 'Chatsworth'),
  ('91313', 'Chatsworth', 'CA', true, 'Chatsworth'),
  ('91316', 'Encino', 'CA', true, 'Encino'),
  ('91321', 'Newhall', 'CA', true, 'Newhall'),
  ('91322', 'Newhall', 'CA', true, 'Newhall'),
  ('91324', 'Northridge', 'CA', true, 'Northridge'),
  ('91325', 'Northridge', 'CA', true, 'Northridge'),
  ('91326', 'Porter Ranch', 'CA', true, 'Porter Ranch'),
  ('91327', 'Northridge', 'CA', true, 'Northridge'),
  ('91328', 'Northridge', 'CA', true, 'Northridge'),
  ('91329', 'Northridge', 'CA', true, 'Northridge'),
  ('91330', 'Northridge', 'CA', true, 'Northridge'),
  ('91331', 'Pacoima', 'CA', true, 'Pacoima'),
  ('91333', 'Pacoima', 'CA', true, 'Pacoima'),
  ('91334', 'Pacoima', 'CA', true, 'Pacoima'),
  ('91335', 'Reseda', 'CA', true, 'Reseda'),
  ('91337', 'Reseda', 'CA', true, 'Reseda'),
  ('91340', 'San Fernando', 'CA', true, 'San Fernando'),
  ('91341', 'San Fernando', 'CA', true, 'San Fernando'),
  ('91342', 'Sylmar', 'CA', true, 'Sylmar'),
  ('91343', 'North Hills', 'CA', true, 'North Hills'),
  ('91344', 'Granada Hills', 'CA', true, 'Granada Hills'),
  ('91345', 'Mission Hills', 'CA', true, 'Mission Hills'),
  ('91346', 'Mission Hills', 'CA', true, 'Mission Hills'),
  ('91350', 'Santa Clarita', 'CA', true, 'Santa Clarita'),
  ('91351', 'Canyon Country', 'CA', true, 'Canyon Country'),
  ('91352', 'Sun Valley', 'CA', true, 'Sun Valley'),
  ('91353', 'Sun Valley', 'CA', true, 'Sun Valley'),
  ('91354', 'Valencia', 'CA', true, 'Valencia'),
  ('91355', 'Valencia', 'CA', true, 'Valencia'),
  ('91356', 'Tarzana', 'CA', true, 'Tarzana'),
  ('91357', 'Tarzana', 'CA', true, 'Tarzana'),
  ('91364', 'Woodland Hills', 'CA', true, 'Woodland Hills'),
  ('91365', 'Woodland Hills', 'CA', true, 'Woodland Hills'),
  ('91367', 'Woodland Hills', 'CA', true, 'Woodland Hills'),
  ('91371', 'Woodland Hills', 'CA', true, 'Woodland Hills'),
  ('91372', 'Calabasas', 'CA', true, 'Calabasas'),
  ('91376', 'Agoura Hills', 'CA', true, 'Agoura Hills'),
  ('91380', 'Santa Clarita', 'CA', true, 'Santa Clarita'),
  ('91381', 'Stevenson Ranch', 'CA', true, 'Stevenson Ranch'),
  ('91382', 'Santa Clarita', 'CA', true, 'Santa Clarita'),
  ('91383', 'Santa Clarita', 'CA', true, 'Santa Clarita'),
  ('91384', 'Castaic', 'CA', true, 'Castaic'),
  ('91385', 'Valencia', 'CA', true, 'Valencia'),
  ('91386', 'Canyon Country', 'CA', true, 'Canyon Country'),
  ('91387', 'Canyon Country', 'CA', true, 'Canyon Country'),
  ('91390', 'Santa Clarita', 'CA', true, 'Santa Clarita'),
  ('91392', 'Sylmar', 'CA', true, 'Sylmar'),
  ('91393', 'North Hills', 'CA', true, 'North Hills'),
  ('91394', 'Granada Hills', 'CA', true, 'Granada Hills'),
  ('91395', 'Mission Hills', 'CA', true, 'Mission Hills'),
  ('91396', 'Winnetka', 'CA', true, 'Winnetka'),
  ('91401', 'Van Nuys', 'CA', true, 'Van Nuys'),
  ('91402', 'Panorama City', 'CA', true, 'Panorama City'),
  ('91403', 'Sherman Oaks', 'CA', true, 'Sherman Oaks'),
  ('91404', 'Van Nuys', 'CA', true, 'Van Nuys'),
  ('91405', 'Van Nuys', 'CA', true, 'Van Nuys'),
  ('91406', 'Van Nuys', 'CA', true, 'Van Nuys'),
  ('91407', 'Van Nuys', 'CA', true, 'Van Nuys'),
  ('91408', 'Van Nuys', 'CA', true, 'Van Nuys'),
  ('91409', 'Van Nuys', 'CA', true, 'Van Nuys'),
  ('91410', 'Van Nuys', 'CA', true, 'Van Nuys'),
  ('91411', 'Van Nuys', 'CA', true, 'Van Nuys'),
  ('91412', 'Panorama City', 'CA', true, 'Panorama City'),
  ('91413', 'Sherman Oaks', 'CA', true, 'Sherman Oaks'),
  ('91416', 'Encino', 'CA', true, 'Encino'),
  ('91423', 'Sherman Oaks', 'CA', true, 'Sherman Oaks'),
  ('91426', 'Encino', 'CA', true, 'Encino'),
  ('91436', 'Encino', 'CA', true, 'Encino'),
  ('91470', 'Van Nuys', 'CA', true, 'Van Nuys'),
  ('91482', 'Van Nuys', 'CA', true, 'Van Nuys'),
  ('91495', 'Sherman Oaks', 'CA', true, 'Sherman Oaks'),
  ('91496', 'Van Nuys', 'CA', true, 'Van Nuys'),
  ('91499', 'Van Nuys', 'CA', true, 'Van Nuys'),
  ('91501', 'Burbank', 'CA', true, 'Burbank'),
  ('91502', 'Burbank', 'CA', true, 'Burbank'),
  ('91503', 'Burbank', 'CA', true, 'Burbank'),
  ('91504', 'Burbank', 'CA', true, 'Burbank'),
  ('91505', 'Burbank', 'CA', true, 'Burbank'),
  ('91506', 'Burbank', 'CA', true, 'Burbank'),
  ('91507', 'Burbank', 'CA', true, 'Burbank'),
  ('91508', 'Burbank', 'CA', true, 'Burbank'),
  ('91510', 'Burbank', 'CA', true, 'Burbank'),
  ('91521', 'Burbank', 'CA', true, 'Burbank'),
  ('91522', 'Burbank', 'CA', true, 'Burbank'),
  ('91523', 'Burbank', 'CA', true, 'Burbank'),
  ('91526', 'Burbank', 'CA', true, 'Burbank'),
  ('91601', 'North Hollywood', 'CA', true, 'North Hollywood'),
  ('91602', 'North Hollywood', 'CA', true, 'North Hollywood'),
  ('91603', 'North Hollywood', 'CA', true, 'North Hollywood'),
  ('91604', 'Studio City', 'CA', true, 'Studio City'),
  ('91605', 'North Hollywood', 'CA', true, 'North Hollywood'),
  ('91606', 'North Hollywood', 'CA', true, 'North Hollywood'),
  ('91607', 'Valley Village', 'CA', true, 'Valley Village'),
  ('91608', 'Universal City', 'CA', true, 'Universal City'),
  ('91609', 'North Hollywood', 'CA', true, 'North Hollywood'),
  ('91610', 'Toluca Lake', 'CA', true, 'Toluca Lake'),
  ('91611', 'North Hollywood', 'CA', true, 'North Hollywood'),
  ('91612', 'North Hollywood', 'CA', true, 'North Hollywood'),
  ('91614', 'Studio City', 'CA', true, 'Studio City'),
  ('91615', 'North Hollywood', 'CA', true, 'North Hollywood'),
  ('91616', 'North Hollywood', 'CA', true, 'North Hollywood'),
  ('91617', 'Valley Village', 'CA', true, 'Valley Village'),
  ('91618', 'North Hollywood', 'CA', true, 'North Hollywood'),
  ('91702', 'Azusa', 'CA', true, 'Azusa'),
  ('91706', 'Baldwin Park', 'CA', true, 'Baldwin Park'),
  ('91711', 'Claremont', 'CA', true, 'Claremont'),
  ('91714', 'City Of Industry', 'CA', true, 'City Of Industry'),
  ('91715', 'City Of Industry', 'CA', true, 'City Of Industry'),
  ('91716', 'City Of Industry', 'CA', true, 'City Of Industry'),
  ('91722', 'Covina', 'CA', true, 'Covina'),
  ('91723', 'Covina', 'CA', true, 'Covina'),
  ('91724', 'Covina', 'CA', true, 'Covina'),
  ('91731', 'El Monte', 'CA', true, 'El Monte'),
  ('91732', 'El Monte', 'CA', true, 'El Monte'),
  ('91733', 'South El Monte', 'CA', true, 'South El Monte'),
  ('91734', 'El Monte', 'CA', true, 'El Monte'),
  ('91735', 'El Monte', 'CA', true, 'El Monte'),
  ('91740', 'Glendora', 'CA', true, 'Glendora'),
  ('91741', 'Glendora', 'CA', true, 'Glendora'),
  ('91744', 'La Puente', 'CA', true, 'La Puente'),
  ('91745', 'Hacienda Heights', 'CA', true, 'Hacienda Heights'),
  ('91746', 'La Puente', 'CA', true, 'La Puente'),
  ('91747', 'La Puente', 'CA', true, 'La Puente'),
  ('91748', 'Rowland Heights', 'CA', true, 'Rowland Heights'),
  ('91749', 'La Puente', 'CA', true, 'La Puente'),
  ('91750', 'La Verne', 'CA', true, 'La Verne'),
  ('91754', 'Monterey Park', 'CA', true, 'Monterey Park'),
  ('91755', 'Monterey Park', 'CA', true, 'Monterey Park'),
  ('91756', 'Monterey Park', 'CA', true, 'Monterey Park'),
  ('91765', 'Diamond Bar', 'CA', true, 'Diamond Bar'),
  ('91766', 'Pomona', 'CA', true, 'Pomona'),
  ('91767', 'Pomona', 'CA', true, 'Pomona'),
  ('91768', 'Pomona', 'CA', true, 'Pomona'),
  ('91769', 'Pomona', 'CA', true, 'Pomona'),
  ('91770', 'Rosemead', 'CA', true, 'Rosemead'),
  ('91771', 'Rosemead', 'CA', true, 'Rosemead'),
  ('91772', 'Rosemead', 'CA', true, 'Rosemead'),
  ('91773', 'San Dimas', 'CA', true, 'San Dimas'),
  ('91775', 'San Gabriel', 'CA', true, 'San Gabriel'),
  ('91776', 'San Gabriel', 'CA', true, 'San Gabriel'),
  ('91778', 'San Gabriel', 'CA', true, 'San Gabriel'),
  ('91780', 'Temple City', 'CA', true, 'Temple City'),
  ('91788', 'Walnut', 'CA', true, 'Walnut'),
  ('91789', 'Walnut', 'CA', true, 'Walnut'),
  ('91790', 'West Covina', 'CA', true, 'West Covina'),
  ('91791', 'West Covina', 'CA', true, 'West Covina'),
  ('91792', 'West Covina', 'CA', true, 'West Covina'),
  ('91793', 'West Covina', 'CA', true, 'West Covina'),
  ('91801', 'Alhambra', 'CA', true, 'Alhambra'),
  ('91802', 'Alhambra', 'CA', true, 'Alhambra'),
  ('91803', 'Alhambra', 'CA', true, 'Alhambra'),
  ('91804', 'Alhambra', 'CA', true, 'Alhambra'),
  ('91896', 'Alhambra', 'CA', true, 'Alhambra'),
  ('91899', 'Alhambra', 'CA', true, 'Alhambra'),
  ('93510', 'Acton', 'CA', true, 'Acton'),
  ('93532', 'Lake Hughes', 'CA', true, 'Lake Hughes'),
  ('93534', 'Lancaster', 'CA', true, 'Lancaster'),
  ('93535', 'Lancaster', 'CA', true, 'Lancaster'),
  ('93536', 'Lancaster', 'CA', true, 'Lancaster'),
  ('93539', 'Lancaster', 'CA', true, 'Lancaster'),
  ('93543', 'Littlerock', 'CA', true, 'Littlerock'),
  ('93544', 'Llano', 'CA', true, 'Llano'),
  ('93550', 'Palmdale', 'CA', true, 'Palmdale'),
  ('93551', 'Palmdale', 'CA', true, 'Palmdale'),
  ('93552', 'Palmdale', 'CA', true, 'Palmdale'),
  ('93553', 'Pearblossom', 'CA', true, 'Pearblossom'),
  ('93563', 'Valyermo', 'CA', true, 'Valyermo'),
  ('93584', 'Lancaster', 'CA', true, 'Lancaster'),
  ('93586', 'Lancaster', 'CA', true, 'Lancaster'),
  ('93590', 'Palmdale', 'CA', true, 'Palmdale'),
  ('93591', 'Palmdale', 'CA', true, 'Palmdale'),
  ('93599', 'Palmdale', 'CA', true, 'Palmdale')
ON CONFLICT DO NOTHING;
