-- Service area seed: San Bernardino County, CA
-- Generated: 2026-06-16
-- Apply via Supabase SQL Editor AFTER 2026-06-16_add_county_to_service_areas.sql
-- county column must already exist before running this migration.

INSERT INTO service_areas (zip, city, state, is_active, name, county)
VALUES
  -- Western Inland Empire
  ('91701', 'Rancho Cucamonga', 'CA', true, 'Rancho Cucamonga', 'San Bernardino'),
  ('91708', 'Chino', 'CA', true, 'Chino', 'San Bernardino'),
  ('91709', 'Chino Hills', 'CA', true, 'Chino Hills', 'San Bernardino'),
  ('91710', 'Chino', 'CA', true, 'Chino', 'San Bernardino'),
  ('91730', 'Rancho Cucamonga', 'CA', true, 'Rancho Cucamonga', 'San Bernardino'),
  ('91737', 'Rancho Cucamonga', 'CA', true, 'Rancho Cucamonga', 'San Bernardino'),
  ('91739', 'Rancho Cucamonga', 'CA', true, 'Rancho Cucamonga', 'San Bernardino'),
  ('91743', 'Ontario', 'CA', true, 'Ontario', 'San Bernardino'),
  ('91758', 'Ontario', 'CA', true, 'Ontario', 'San Bernardino'),
  ('91761', 'Ontario', 'CA', true, 'Ontario', 'San Bernardino'),
  ('91762', 'Ontario', 'CA', true, 'Ontario', 'San Bernardino'),
  ('91763', 'Montclair', 'CA', true, 'Montclair', 'San Bernardino'),
  ('91764', 'Ontario', 'CA', true, 'Ontario', 'San Bernardino'),
  ('91784', 'Upland', 'CA', true, 'Upland', 'San Bernardino'),
  ('91785', 'Upland', 'CA', true, 'Upland', 'San Bernardino'),
  ('91786', 'Upland', 'CA', true, 'Upland', 'San Bernardino'),
  -- Mountain communities
  ('92305', 'Angelus Oaks', 'CA', true, 'Angelus Oaks', 'San Bernardino'),
  ('92314', 'Big Bear City', 'CA', true, 'Big Bear City', 'San Bernardino'),
  ('92315', 'Big Bear Lake', 'CA', true, 'Big Bear Lake', 'San Bernardino'),
  ('92317', 'Blue Jay', 'CA', true, 'Blue Jay', 'San Bernardino'),
  ('92321', 'Cedar Glen', 'CA', true, 'Cedar Glen', 'San Bernardino'),
  ('92322', 'Cedarpines Park', 'CA', true, 'Cedarpines Park', 'San Bernardino'),
  ('92325', 'Crestline', 'CA', true, 'Crestline', 'San Bernardino'),
  ('92326', 'Crest Park', 'CA', true, 'Crest Park', 'San Bernardino'),
  ('92333', 'Fawnskin', 'CA', true, 'Fawnskin', 'San Bernardino'),
  ('92339', 'Forest Falls', 'CA', true, 'Forest Falls', 'San Bernardino'),
  ('92341', 'Green Valley Lake', 'CA', true, 'Green Valley Lake', 'San Bernardino'),
  ('92352', 'Lake Arrowhead', 'CA', true, 'Lake Arrowhead', 'San Bernardino'),
  ('92356', 'Lucerne Valley', 'CA', true, 'Lucerne Valley', 'San Bernardino'),
  ('92358', 'Lytle Creek', 'CA', true, 'Lytle Creek', 'San Bernardino'),
  ('92378', 'Rimforest', 'CA', true, 'Rimforest', 'San Bernardino'),
  ('92382', 'Running Springs', 'CA', true, 'Running Springs', 'San Bernardino'),
  ('92385', 'Skyforest', 'CA', true, 'Skyforest', 'San Bernardino'),
  ('92386', 'Sugarloaf', 'CA', true, 'Sugarloaf', 'San Bernardino'),
  ('92391', 'Twin Peaks', 'CA', true, 'Twin Peaks', 'San Bernardino'),
  ('92397', 'Wrightwood', 'CA', true, 'Wrightwood', 'San Bernardino'),
  -- San Bernardino Valley / Inland Empire East
  ('92313', 'Grand Terrace', 'CA', true, 'Grand Terrace', 'San Bernardino'),
  ('92316', 'Bloomington', 'CA', true, 'Bloomington', 'San Bernardino'),
  ('92318', 'Bryn Mawr', 'CA', true, 'Bryn Mawr', 'San Bernardino'),
  ('92324', 'Colton', 'CA', true, 'Colton', 'San Bernardino'),
  ('92331', 'Fontana', 'CA', true, 'Fontana', 'San Bernardino'),
  ('92334', 'Fontana', 'CA', true, 'Fontana', 'San Bernardino'),
  ('92335', 'Fontana', 'CA', true, 'Fontana', 'San Bernardino'),
  ('92336', 'Fontana', 'CA', true, 'Fontana', 'San Bernardino'),
  ('92337', 'Fontana', 'CA', true, 'Fontana', 'San Bernardino'),
  ('92346', 'Highland', 'CA', true, 'Highland', 'San Bernardino'),
  ('92350', 'Loma Linda', 'CA', true, 'Loma Linda', 'San Bernardino'),
  ('92354', 'Loma Linda', 'CA', true, 'Loma Linda', 'San Bernardino'),
  ('92357', 'Loma Linda', 'CA', true, 'Loma Linda', 'San Bernardino'),
  ('92359', 'Mentone', 'CA', true, 'Mentone', 'San Bernardino'),
  ('92373', 'Redlands', 'CA', true, 'Redlands', 'San Bernardino'),
  ('92374', 'Redlands', 'CA', true, 'Redlands', 'San Bernardino'),
  ('92375', 'Redlands', 'CA', true, 'Redlands', 'San Bernardino'),
  ('92376', 'Rialto', 'CA', true, 'Rialto', 'San Bernardino'),
  ('92377', 'Rialto', 'CA', true, 'Rialto', 'San Bernardino'),
  ('92399', 'Yucaipa', 'CA', true, 'Yucaipa', 'San Bernardino'),
  -- High Desert
  ('92301', 'Adelanto', 'CA', true, 'Adelanto', 'San Bernardino'),
  ('92307', 'Apple Valley', 'CA', true, 'Apple Valley', 'San Bernardino'),
  ('92308', 'Apple Valley', 'CA', true, 'Apple Valley', 'San Bernardino'),
  ('92311', 'Barstow', 'CA', true, 'Barstow', 'San Bernardino'),
  ('92312', 'Barstow', 'CA', true, 'Barstow', 'San Bernardino'),
  ('92327', 'Daggett', 'CA', true, 'Daggett', 'San Bernardino'),
  ('92329', 'Phelan', 'CA', true, 'Phelan', 'San Bernardino'),
  ('92340', 'Hesperia', 'CA', true, 'Hesperia', 'San Bernardino'),
  ('92342', 'Helendale', 'CA', true, 'Helendale', 'San Bernardino'),
  ('92344', 'Hesperia', 'CA', true, 'Hesperia', 'San Bernardino'),
  ('92345', 'Hesperia', 'CA', true, 'Hesperia', 'San Bernardino'),
  ('92347', 'Hinkley', 'CA', true, 'Hinkley', 'San Bernardino'),
  ('92368', 'Oro Grande', 'CA', true, 'Oro Grande', 'San Bernardino'),
  ('92371', 'Phelan', 'CA', true, 'Phelan', 'San Bernardino'),
  ('92392', 'Victorville', 'CA', true, 'Victorville', 'San Bernardino'),
  ('92393', 'Victorville', 'CA', true, 'Victorville', 'San Bernardino'),
  ('92394', 'Victorville', 'CA', true, 'Victorville', 'San Bernardino'),
  ('92395', 'Victorville', 'CA', true, 'Victorville', 'San Bernardino'),
  -- Desert communities
  ('92256', 'Morongo Valley', 'CA', true, 'Morongo Valley', 'San Bernardino'),
  ('92277', 'Twentynine Palms', 'CA', true, 'Twentynine Palms', 'San Bernardino'),
  ('92278', 'Twentynine Palms', 'CA', true, 'Twentynine Palms', 'San Bernardino'),
  ('92284', 'Yucca Valley', 'CA', true, 'Yucca Valley', 'San Bernardino'),
  ('92285', 'Landers', 'CA', true, 'Landers', 'San Bernardino'),
  ('92286', 'Yucca Valley', 'CA', true, 'Yucca Valley', 'San Bernardino'),
  ('92309', 'Baker', 'CA', true, 'Baker', 'San Bernardino'),
  ('92310', 'Fort Irwin', 'CA', true, 'Fort Irwin', 'San Bernardino'),
  ('92323', 'Cima', 'CA', true, 'Cima', 'San Bernardino'),
  ('92332', 'Essex', 'CA', true, 'Essex', 'San Bernardino'),
  ('92338', 'Ludlow', 'CA', true, 'Ludlow', 'San Bernardino'),
  ('92363', 'Needles', 'CA', true, 'Needles', 'San Bernardino'),
  ('92364', 'Nipton', 'CA', true, 'Nipton', 'San Bernardino'),
  ('92365', 'Newberry Springs', 'CA', true, 'Newberry Springs', 'San Bernardino'),
  ('92366', 'Mountain Pass', 'CA', true, 'Mountain Pass', 'San Bernardino'),
  ('92369', 'Patton', 'CA', true, 'Patton', 'San Bernardino'),
  ('92372', 'Pioneertown', 'CA', true, 'Pioneertown', 'San Bernardino'),
  -- San Bernardino city
  ('92401', 'San Bernardino', 'CA', true, 'San Bernardino', 'San Bernardino'),
  ('92403', 'San Bernardino', 'CA', true, 'San Bernardino', 'San Bernardino'),
  ('92404', 'San Bernardino', 'CA', true, 'San Bernardino', 'San Bernardino'),
  ('92405', 'San Bernardino', 'CA', true, 'San Bernardino', 'San Bernardino'),
  ('92406', 'San Bernardino', 'CA', true, 'San Bernardino', 'San Bernardino'),
  ('92407', 'San Bernardino', 'CA', true, 'San Bernardino', 'San Bernardino'),
  ('92408', 'San Bernardino', 'CA', true, 'San Bernardino', 'San Bernardino'),
  ('92410', 'San Bernardino', 'CA', true, 'San Bernardino', 'San Bernardino'),
  ('92411', 'San Bernardino', 'CA', true, 'San Bernardino', 'San Bernardino'),
  ('92413', 'San Bernardino', 'CA', true, 'San Bernardino', 'San Bernardino'),
  ('92415', 'San Bernardino', 'CA', true, 'San Bernardino', 'San Bernardino'),
  ('92418', 'San Bernardino', 'CA', true, 'San Bernardino', 'San Bernardino'),
  ('92423', 'San Bernardino', 'CA', true, 'San Bernardino', 'San Bernardino'),
  ('92427', 'San Bernardino', 'CA', true, 'San Bernardino', 'San Bernardino')
ON CONFLICT DO NOTHING;
