import { supabase } from "../../lib/supabase";
import { supabaseAdmin } from "../../lib/supabaseAdmin";

const db = supabaseAdmin ?? supabase;

// ─── Referral analytics ────────────────────────────────────────────────────

export interface ReferralCodePerformance {
  code: string;
  owner_type: "customer" | "partner";
  partner_name: string | null;
  lead_count: number;
  conversion_count: number;
}

export interface ReferralAnalytics {
  by_code: ReferralCodePerformance[];
  pending_rewards_count: number;
  pending_rewards_value_cents: number;
  partner_performance: ReferralCodePerformance[];
}

export async function getReferralAnalytics(): Promise<ReferralAnalytics> {
  const [{ data: codes }, { data: referrals }, { data: pendingRewards }] = await Promise.all([
    db.from("referral_codes").select("id, code, owner_type, partner_name"),
    db.from("referrals").select("referral_code_id, status"),
    db.from("referral_rewards").select("amount_cents").eq("status", "pending"),
  ]);

  const codeMap: Record<string, ReferralCodePerformance> = {};
  (codes ?? []).forEach((c: any) => {
    codeMap[c.id] = { code: c.code, owner_type: c.owner_type, partner_name: c.partner_name, lead_count: 0, conversion_count: 0 };
  });

  (referrals ?? []).forEach((r: any) => {
    const entry = codeMap[r.referral_code_id];
    if (!entry) return;
    entry.lead_count++;
    if (["converted", "rewarded"].includes(r.status)) entry.conversion_count++;
  });

  const byCode = Object.values(codeMap).sort((a, b) => b.lead_count - a.lead_count);
  const partnerPerformance = byCode.filter((c) => c.owner_type === "partner");

  const pendingCount = (pendingRewards ?? []).length;
  const pendingValue = (pendingRewards ?? []).reduce((sum: number, r: any) => sum + (r.amount_cents ?? 0), 0);

  return {
    by_code: byCode,
    pending_rewards_count: pendingCount,
    pending_rewards_value_cents: pendingValue,
    partner_performance: partnerPerformance,
  };
}

// ─── Route analytics ────────────────────────────────────────────────────────

export interface RouteAnalytics {
  window_days: number;
  total_routes: number;
  total_estimated_miles: number;
  total_estimated_drive_minutes: number;
  published_with_warnings_count: number;
  auto_generated_count: number;
  auto_published_count: number;
  smart_optimize: {
    runs: number;
    total_distance_saved_miles: number;
    total_time_saved_minutes: number;
  };
}

export async function getRouteAnalytics(windowDays = 30): Promise<RouteAnalytics> {
  const since = new Date(Date.now() - windowDays * 24 * 60 * 60 * 1000).toISOString().slice(0, 10);

  const [{ data: routes }, { data: auditRows }] = await Promise.all([
    db.from("routes").select("id, status, total_distance_miles, total_duration_minutes, conflict_notes, date").gte("date", since),
    db.from("route_audit_log").select("action, metadata, actor_role, created_at").gte("created_at", `${since}T00:00:00Z`),
  ]);

  const allRoutes = routes ?? [];
  const totalMiles = allRoutes.reduce((sum: number, r: any) => sum + (r.total_distance_miles ?? 0), 0);
  const totalMinutes = allRoutes.reduce((sum: number, r: any) => sum + (r.total_duration_minutes ?? 0), 0);
  const publishedWithWarnings = allRoutes.filter(
    (r: any) => r.status === "published" && Array.isArray(r.conflict_notes) && r.conflict_notes.length > 0,
  ).length;

  const autoGenerated = (auditRows ?? []).filter((a: any) => a.action === "automation_route_generated").length;
  const autoPublished = (auditRows ?? []).filter((a: any) => a.action === "auto_published" && a.actor_role === "system").length;
  const optimizeRuns = (auditRows ?? []).filter((a: any) => a.action === "smart_reorder" || a.action === "automation_smart_reorder");

  const distanceSaved = optimizeRuns.reduce((sum: number, a: any) => sum + (a.metadata?.distance_saved_miles ?? 0), 0);
  const timeSaved = optimizeRuns.reduce((sum: number, a: any) => sum + (a.metadata?.time_saved_minutes ?? 0), 0);

  return {
    window_days: windowDays,
    total_routes: allRoutes.length,
    total_estimated_miles: Math.round(totalMiles * 10) / 10,
    total_estimated_drive_minutes: Math.round(totalMinutes),
    published_with_warnings_count: publishedWithWarnings,
    auto_generated_count: autoGenerated,
    auto_published_count: autoPublished,
    smart_optimize: {
      runs: optimizeRuns.length,
      total_distance_saved_miles: Math.round(distanceSaved * 10) / 10,
      total_time_saved_minutes: Math.round(timeSaved),
    },
  };
}

// ─── CRM analytics ──────────────────────────────────────────────────────────

export interface CrmAnalytics {
  leads_by_status: Record<string, number>;
  assigned_leads_by_staff: { staff_id: string; staff_name: string; count: number }[];
  overdue_followups_count: number;
  conversion_candidates_count: number;
}

export async function getCrmAnalytics(): Promise<CrmAnalytics> {
  const nowIso = new Date().toISOString();

  const [{ data: leads }, { data: followups }, { data: referrals }] = await Promise.all([
    db.from("leads").select("status, assigned_to"),
    db.from("lead_followups").select("id").eq("status", "pending").lt("due_at", nowIso),
    db.from("referrals").select("id").eq("status", "conversion_candidate"),
  ]);

  const leadsByStatus: Record<string, number> = {};
  const assignedCounts: Record<string, number> = {};
  (leads ?? []).forEach((l: any) => {
    leadsByStatus[l.status] = (leadsByStatus[l.status] ?? 0) + 1;
    if (l.assigned_to) assignedCounts[l.assigned_to] = (assignedCounts[l.assigned_to] ?? 0) + 1;
  });

  const staffIds = Object.keys(assignedCounts);
  const { data: staffProfiles } = staffIds.length
    ? await db.from("profiles").select("id, name, email").in("id", staffIds)
    : { data: [] };

  const staffMap: Record<string, string> = {};
  (staffProfiles ?? []).forEach((p: any) => { staffMap[p.id] = p.name || p.email; });

  const assignedLeadsByStaff = Object.entries(assignedCounts)
    .map(([staffId, count]) => ({ staff_id: staffId, staff_name: staffMap[staffId] ?? "Unknown", count }))
    .sort((a, b) => b.count - a.count);

  return {
    leads_by_status: leadsByStatus,
    assigned_leads_by_staff: assignedLeadsByStaff,
    overdue_followups_count: (followups ?? []).length,
    conversion_candidates_count: (referrals ?? []).length,
  };
}
